version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - echo $READTHEDOCS_OUTPUT
      - pwd