version: 2
formats: [htmlzip, pdf]
sphinx:
   configuration: docs/conf.py
python:
   install:
     - requirements: docs/requirements.txt
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - bash ./scripts/pre_install.sh
    build:
      # The default commands for generating the HTML and pdf formats will still run.
      htmlzip:
        - echo "Override default build command for htmlzip format"
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip/
        - echo "Hello, world! $READTHEDOCS_OUTPUT" > $READTHEDOCS_OUTPUT/htmlzip/index.zip
    post_build:
      - curl -X POST \
        -F "project=${READTHEDOCS_PROJECT}" \
        -F "version=${READTHEDOCS_VERSION}" https://example.com/webhooks/readthedocs/