# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version and other tools you might need

# Note:
# Recommend setting the following env variable for local builds to suppress
# unhelpful warnings when e.g. dataclass attributes are also documented in
# docstrings:
# `export SPHINX_APIDOC_OPTIONS=members,show-inheritance`
# in readthedocs.org, this env variable is set through admin/Environment Variables
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  # commands:
  #   - pip install -r docs/requirements.txt
  #   - cd docs && make html
  #   - mkdir $READTHEDOCS_OUTPUT
  #   - echo "$READTHEDOCS_VIRTUALENV_PATH"
    # - cp -r docs/_build/html $READTHEDOCS_OUTPUT/

sphinx:
  configuration: doc/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip