version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pwd
      - echo "Pre-build step"
    # post_checkout:
    #   - echo $READTHEDOCS_OUTPUT
    #   - pwd
    post_build:
      - pwd
      - echo "Post-build step"