name: "RTD check"
on:
  merge_group:
    types:
      - checks_requested
  pull_request: {}

jobs:
  rtd:
    runs-on: ubuntu-22.04
    env:
      PYTHON_VERSION: "3.10"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Check status
      run: |
        sleep 120
        COMMIT_HASH=${{ github.workflow_sha }}
        while [[ "$SUCCESS" != "true" && "$SUCCESS" != "false" ]]; do
          sleep 120
          echo "Checking build status for commit $COMMIT_HASH..."
          RESPONSE=$(curl -s "https://readthedocs.org/api/v3/projects/runora95-readthedocstutorial/builds")
          SUCCESS=$(echo "$RESPONSE" | jq -r --arg COMMIT "$COMMIT_HASH" '.results[] | select(.commit == $COMMIT) | .success')
        done
        if [ "$SUCCESS" == "true" ]; then
          echo "Build for commit $COMMIT_HASH was successful."
        else
          echo "Build for commit $COMMIT_HASH failed."
        fi
       
       
#        RESPONSE=$(curl -s "https://readthedocs.org/api/v3/projects/runora95-readthedocstutorial/builds")
        # SUCCESS=$(echo "$RESPONSE" | jq -r --arg COMMIT "$COMMIT_HASH" '.results[] | select(.commit == $COMMIT) | .success')

        # if [ "$SUCCESS" == "true" ]; then
        #   echo "Build for commit $COMMIT_HASH was successful."
        # else
        #   RESPONSE=$(curl -s "https://readthedocs.org/api/v3/projects/runora95-readthedocstutorial/builds")
        #   SUCCESS=$(echo "$RESPONSE" | jq -r --arg COMMIT "$COMMIT_HASH" '.results[] | select(.commit == $COMMIT) | .success')

        # fi
